version: '3.9'

services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: npm
    restart: unless-stopped
    ports:
      - "4873:4873"
    volumes:
      - './storage/:/verdaccio/storage'
